### ISSUE TITLE
error 017: undefined symbol "Fox"

### ISSUE THREAD

**Issue by Hamiiziii** [AbyssMorgan/SAMP#1]
#define FoxForeach(%0,%1)				for(new %0 = Fox%1[0], i_%0 = 0; i_%0 <= Fox%1Upp; i_%0++, %0 = Fox%1[i_%0])
@AbyssMorgan

**Comment by AbyssMorgan** [comment]
FoxForeach macro required syntax without any extra spaces in arguments

Examaple:
```
FoxForeach(variable, Character ) //bad
FoxForeach(variable, Player) //bad
FoxForeach(variable,Bot ) //bad

FoxForeach(variable,Character) //ok
FoxForeach(variable,Player) //ok
FoxForeach(variable,Bot) //ok
```
